import { readFileSync } from 'fs';
import { join } from 'path';
import { DocGeneratorService } from '../../src/modules/services/DocGeneratorService.js';

const FIXTURES = join(process.cwd(), 'tests', 'services', '__fixtures__');

/**
 * @param {string} name
 * @returns {string}
 */
function fixture(name) {
    return readFileSync(join(FIXTURES, name), 'utf8');
}

/**
 * @param {string} text
 * @returns {string}
 */
function withoutDate(text) {
    return text.replace(/Generated by Resonance on [^*<]+/g, 'Generated by Resonance on DATE')
        .replace(/Generated on [^<]+/g, 'Generated on DATE');
}

const collection = {
    id: 'col-1',
    name: 'Golden & API',
    description: 'Covers <every> markdown branch',
    baseUrl: 'https://api.example.com',
    defaultHeaders: { 'X-Tenant': 'acme', Accept: 'application/json' },
    endpoints: [
        {
            id: 'root-get',
            method: 'GET',
            name: 'Health',
            path: '/health',
            summary: 'Liveness probe'
        },
        {
            id: 'root-ws',
            method: 'WEBSOCKET',
            name: 'Socket',
            path: '/ws'
        }
    ],
    folders: [
        {
            name: 'Users',
            endpoints: [
                {
                    id: 'users-list',
                    method: 'GET',
                    name: 'List users',
                    path: '/users',
                    description: 'Paged list',
                    parameters: {
                        query: {
                            page: { type: 'integer', required: true, description: 'Page number', example: 1 },
                            q: { schema: { type: 'string' } }
                        },
                        header: {
                            accept: { example: 'text/plain', description: 'Overridden by persisted' },
                            'X-Trace': { description: 'Trace id' }
                        }
                    }
                },
                {
                    id: 'users-update',
                    method: 'PUT',
                    path: '/users/{id}/roles/{{role}}',
                    parameters: {
                        path: {
                            id: { type: 'string', description: 'User id', example: '42' },
                            role: { required: false }
                        }
                    },
                    requestBody: {
                        contentType: 'application/json',
                        example: { role: 'admin' }
                    }
                }
            ],
            folders: [
                {
                    name: 'Admin',
                    endpoints: [
                        {
                            id: 'admin-post',
                            method: 'POST',
                            name: 'Create admin',
                            path: '/admins',
                            requestBody: { example: 'not json' }
                        },
                        {
                            id: 'admin-patch',
                            method: 'PATCH',
                            name: 'Patch admin',
                            path: '/admins/{id}'
                        }
                    ]
                }
            ]
        },
        {
            name: 'Empty',
            endpoints: [{ id: 'grpc', method: 'GRPC', name: 'Only grpc', path: '/g' }]
        }
    ]
};

const persisted = {
    'users-list': {
        queryParams: [{ key: 'page', value: '3' }, { key: 'q', value: 'x', enabled: false }],
        headers: [{ key: 'Accept', value: 'application/xml' }, { key: 'X-Off', value: 'no', enabled: false }, { key: 'Accept', value: 'dup' }],
        responseSchema: { type: 'array', items: { type: 'object' } }
    },
    'users-update': {
        pathParams: [{ key: 'id', value: '7' }],
        modifiedBody: '{"role":"owner"}'
    },
    'admin-patch': {
        modifiedBody: '{"patched":true}',
        responseSchema: { type: 'object' }
    }
};

const template = '<title>{{TITLE}}</title><h1>{{TITLE}}</h1>{{DESCRIPTION}}{{BASE_URL}}<nav>{{TOC}}</nav><main>{{CONTENT}}</main><footer>Generated on {{DATE}}</footer>';

describe('DocGeneratorService golden output', () => {
    let service;

    beforeEach(() => {
        const repository = {
            getAllPersistedEndpointData: jest.fn(async (collectionId, endpointId) => persisted[endpointId] ?? null)
        };
        service = new DocGeneratorService(repository);
        Object.keys(DocGeneratorService).forEach(key => {
            if (key.startsWith('_cached_')) {
                delete DocGeneratorService[key];
            }
        });
        global.fetch = jest.fn().mockResolvedValue({ ok: true, text: () => Promise.resolve(template) });
    });

    test('markdown without persisted data or code samples', async () => {
        const markdown = await service.generateMarkdown(collection);

        expect(withoutDate(markdown)).toBe(fixture('docgen.plain.md'));
    });

    test('markdown with persisted data and code samples', async () => {
        const markdown = await service.generateMarkdown(collection, {
            includePersistedData: true,
            languages: ['curl', 'python', 'javascript-fetch', 'not-a-language']
        });

        expect(withoutDate(markdown)).toBe(fixture('docgen.full.md'));
    });

    test('html with persisted data and code samples', async () => {
        const html = await service.generateHtml(collection, {
            includePersistedData: true,
            languages: ['curl', 'javascript-fetch', 'not-a-language']
        });

        expect(withoutDate(html)).toBe(fixture('docgen.full.html'));
    });
});
