openapi: 3.0.0
info:
  title: Test API
  version: 1.0.0
  description: Test API for path parameter functionality

servers:
  - url: https://api.example.com

paths:
  /users/{userId}:
    get:
      summary: Get user by ID
      parameters:
        - name: userId
          in: path
          required: true
          description: The user ID
          schema:
            type: string
          example: "123"
        - name: include
          in: query
          required: false
          description: Additional data to include
          schema:
            type: string
          example: "profile"
      responses:
        '200':
          description: User data

  /posts/{postId}/comments/{commentId}:
    get:
      summary: Get specific comment on a post
      parameters:
        - name: postId
          in: path
          required: true
          description: The post ID
          schema:
            type: integer
          example: 456
        - name: commentId
          in: path
          required: true
          description: The comment ID
          schema:
            type: integer
          example: 789
        - name: format
          in: query
          required: false
          description: Response format
          schema:
            type: string
            enum: [json, xml]
          example: "json"
      responses:
        '200':
          description: Comment data