name: db-mobile-resonance
base: core22
version: '2.3.0'
title: Resonance
summary: Test and explore web services
description: |
  Resonance is a local-first, zero-account API client application designed to provide
  an excellent user experience for testing and interacting with web services.

  Features:
  - Import collections from OpenAPI 3.0 specifications and Postman collections
  - Environment management with variable templating
  - Multiple authentication methods (Bearer, Basic, API keys, OAuth 2.0, Digest)
  - Code generation in 9 languages
  - GraphQL support with dedicated query editor
  - gRPC support with server reflection
  - Collection runner for batch request execution with variable chaining
  - Built-in mock server for testing
  - Workspace tabs for managing multiple concurrent requests
  - Request history with search and replay
  - Performance metrics with detailed timing breakdown
  - HTTP proxy support
  - Four theme options: light, dark, system-adaptive, and black (OLED)
  - Available in English, German, Spanish, French, and Italian

grade: stable
confinement: strict
icon: assets/icons/icon_256x256.png

contact: mailto:dennis.bluemer@ducart.de
license: MIT
website: https://db-mobile.github.io/resonance
source-code: https://github.com/db-mobile/resonance
issues: https://github.com/db-mobile/resonance/issues

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.1
  /usr/share/libdrm:
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/graphics/drirc.d
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/graphics/X11/XErrorDB
  /usr/share/X11/locale:
    symlink: $SNAP/graphics/X11/locale

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]

apps:
  db-mobile-resonance:
    command-chain:
      - bin/graphics-core22-wrapper
    command: usr/bin/resonance
    desktop: usr/share/applications/io.github.db_mobile.resonance.desktop
    extensions: [gnome]
    plugs:
      - graphics-core22
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - opengl
      - gsettings
      - network
      - network-bind

package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

plugs:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22

parts:
  db-mobile-resonance:
    plugin: dump
    build-snaps:
      - node/20/stable
      - rustup/latest/stable
    build-packages:
      - curl
      - wget
      - file
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - libwebkit2gtk-4.1-dev
      - build-essential
      - libxdo-dev
      - dpkg
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
      - libssl3
      - libproxy1v5
    source: .
    override-build: |
      set -eu
      rustup default stable
      npm install
      npm run tauri build -- --bundles deb
      dpkg -x src-tauri/target/release/bundle/deb/*.deb $SNAPCRAFT_PART_INSTALL/

      mkdir -p $CRAFT_PART_INSTALL/usr/share/applications
      cp assets/desktop/io.github.db_mobile.resonance.desktop $CRAFT_PART_INSTALL/usr/share/applications/io.github.db_mobile.resonance.desktop
      sed -i 's/^Exec=.*/Exec=resonance/' $CRAFT_PART_INSTALL/usr/share/applications/io.github.db_mobile.resonance.desktop
      sed -i 's/^Icon=.*/Icon=io.github.db_mobile.resonance/' $CRAFT_PART_INSTALL/usr/share/applications/io.github.db_mobile.resonance.desktop

      # Install icons
      mkdir -p $CRAFT_PART_INSTALL/usr/share/icons/hicolor/32x32/apps
      mkdir -p $CRAFT_PART_INSTALL/usr/share/icons/hicolor/128x128/apps
      mkdir -p $CRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps
      mkdir -p $CRAFT_PART_INSTALL/usr/share/icons/hicolor/512x512/apps
      cp assets/icons/icon_32x32.png $CRAFT_PART_INSTALL/usr/share/icons/hicolor/32x32/apps/io.github.db_mobile.resonance.png
      cp assets/icons/icon_128x128.png $CRAFT_PART_INSTALL/usr/share/icons/hicolor/128x128/apps/io.github.db_mobile.resonance.png
      cp assets/icons/icon_256x256.png $CRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps/io.github.db_mobile.resonance.png
      cp assets/icons/icon_512x512.png $CRAFT_PART_INSTALL/usr/share/icons/hicolor/512x512/apps/io.github.db_mobile.resonance.png

  graphics-core22:
    after: [db-mobile-resonance]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22 nvidia-core22
      mkdir -p "${CRAFT_PRIME}/graphics"
    prime:
      - bin/graphics-core22-wrapper
