name: db-mobile-resonance
base: core24
version: '2.0.1'
title: Resonance
summary: Test and explore web services
description: |
  Resonance is a local-first, zero-account API client application designed to provide
  an excellent user experience for testing and interacting with web services.

  Features:
  - Import collections from OpenAPI 3.0 specifications and Postman collections
  - Environment management with variable templating
  - Multiple authentication methods (Bearer, Basic, API keys, OAuth 2.0, Digest)
  - Code generation in 9 languages
  - GraphQL support with dedicated query editor
  - Built-in mock server for testing
  - Workspace tabs for managing multiple concurrent requests
  - Request history with search and replay
  - Performance metrics with detailed timing breakdown
  - HTTP proxy support
  - Four theme options: light, dark, system-adaptive, and blueprint
  - Available in English, German, Spanish, French, and Italian

grade: stable
confinement: strict
icon: assets/icons/icon_256x256.png

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

apps:
  db-mobile-resonance:
    command: usr/bin/resonance
    desktop: usr/share/applications/io.github.db_mobile.resonance.desktop
    extensions:
      - gnome
    plugs:
      - network
      - network-bind

parts:
  db-mobile-resonance:
    plugin: nil
    source: .
    build-packages:
      - curl
      - wget
      - file
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - libwebkit2gtk-4.1-dev
      - build-essential
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
      - librsvg2-2
      - libssl3
    override-build: |
      # Install Node.js
      curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
      apt-get install -y nodejs

      # Install Rust
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      export PATH="$HOME/.cargo/bin:$PATH"

      # Build the application
      cd $CRAFT_PART_SRC
      npm ci
      npm run build
      npm run build:tauri -- --no-bundle

      # Install the binary
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      cp src-tauri/target/release/resonance $CRAFT_PART_INSTALL/usr/bin/

      # Install desktop file
      mkdir -p $CRAFT_PART_INSTALL/usr/share/applications
      cat > $CRAFT_PART_INSTALL/usr/share/applications/io.github.db_mobile.resonance.desktop << EOF
      [Desktop Entry]
      Name=Resonance
      Comment=A local-first, zero-account API client
      Exec=resonance
      Icon=\${SNAP}/usr/share/icons/hicolor/256x256/apps/io.github.db_mobile.resonance.png
      Type=Application
      Categories=Development;Network;
      StartupNotify=true
      EOF

      # Install icons
      mkdir -p $CRAFT_PART_INSTALL/usr/share/icons/hicolor/32x32/apps
      mkdir -p $CRAFT_PART_INSTALL/usr/share/icons/hicolor/128x128/apps
      mkdir -p $CRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps
      mkdir -p $CRAFT_PART_INSTALL/usr/share/icons/hicolor/512x512/apps
      cp assets/icons/icon_32x32.png $CRAFT_PART_INSTALL/usr/share/icons/hicolor/32x32/apps/io.github.db_mobile.resonance.png
      cp assets/icons/icon_128x128.png $CRAFT_PART_INSTALL/usr/share/icons/hicolor/128x128/apps/io.github.db_mobile.resonance.png
      cp assets/icons/icon_256x256.png $CRAFT_PART_INSTALL/usr/share/icons/hicolor/256x256/apps/io.github.db_mobile.resonance.png
      cp assets/icons/icon_512x512.png $CRAFT_PART_INSTALL/usr/share/icons/hicolor/512x512/apps/io.github.db_mobile.resonance.png

      # Install metainfo
      mkdir -p $CRAFT_PART_INSTALL/usr/share/metainfo
      cp assets/appdata/io.github.db_mobile.resonance.metainfo.xml $CRAFT_PART_INSTALL/usr/share/metainfo/
